url_shortener/models.py
from extensions import db
from datetime import datetime
import string
import random


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(256))
    short_url = db.Column(db.String(5), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_url()

    def generate_short_url(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(random.choices(characters, k=5))
        link = self.query.filter_by(short_url=short_url).first()
        if link:
            return self.generate_short_url()

        return short_url

url_shortener/__init__.py
from flask import Flask
from extensions import db
from routes import short


def create_app(config_file='settings.py'):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///sqlite.db'
    db.init_app(app)
    app.app_context().push()

    # db.create_all()

    app.register_blueprint(short)
    return app


if __name__ == "__main__":
    App = create_app()
    App.run(debug=True)

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect

from models import Link
from extensions import db
from authenticate import requires_auth


short = Blueprint('short', __name__)


@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits = link.visits + 1
    db.session.commit()
    return redirect(link.original_url)


@short.route('/')
def index():
    return render_template('index.html')


@short.route('/add_link', methods=["POST"])
@requires_auth
def add_link():
    original_url = request.form['original_url']
    is_link_present = Link.query.filter_by(original_url=original_url).first()
    if not is_link_present:
        link = Link(original_url=original_url)
        db.session.add(link)
        db.session.commit()

    return render_template('link_added.html', new_link=is_link_present.short_url, original_url=original_url)


@short.route('/stats')
@requires_auth
def stats():
    links = Link.query.all()

    return render_template('stats.html', links=links)


@short.errorhandler(404)
def page_not_found(e):
    return '<h1> 404</h1>', 404

url_shortener/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>URL SHORTENER</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
</head>

<body>
    <section class="section">
        <div class="container">
            <form method="POST" action="{{ url_for('short.add_link') }}">
                <div class="field">
                    <label class="label">Original URL</label>
                    <div class="control">
                        <input class="input" type="text" name="original_url">
                    </div>

                </div>
                <div class="control">
                    <button type="submit" class="button is-info">Shorten</button>
                </div>

            </form>
        </div>
    </section>
</body>

</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SHORTENED URL</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  </head>
  <body>
  <section class="section">
    <div class="container">
            <div class="field">
                <label class="label">Original URL</label>
                <div class="control">
                    <input class="input" type="text" name="original_url" value="{{ original_url }}">
                </div>
            </div>
            <div class="field">
                    <label class="label">New URL</label>
                    <div class="control">
                        <input class="input" type="text" name="original_url" value="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}">
                    </div>
            </div>
    </div>
  </section>
  </body>
</html>

url_shortener/templates/stats.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>STATS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
</head>

<body>
    <section class="section">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>Original URL</th>
                        <th>Short URL</th>
                        <th>Visits</th>
                    </tr>
                </thead>
                <tbody>
                    {% for link in links %}
                    <tr>
                        <td>{{ link.original_url }}</td>
                        <td>{{ url_for('short.redirect_to_url', short_url=link.short_url, _external=True) }}</td>
                        <td>{{ link.visits }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</body>

</html>